### ISSUE TITLE
i can't search content

### ISSUE THREAD

**Issue by nomadli** [benhowdle89/jekyll-search-demo#1]
hi, i add search js into my blog. i can't search anything.
in search.html file

<script>
    var JEKYLL_POSTS = [];
    {% for post in site.posts %}
    JEKYLL_POSTS.push({
        title: "{{ post.title }}",
        link: "{{ post.url | prepend: site.baseurl }}",
        content: "{{ post.content | strip_newlines | strip_html }}"
    }); 
    {% endfor %}
</script>

when i remove the line  content: "{{ post.content | strip_newlines | strip_html }}"
it work, can you help me?

My English is very poor, are you understand me。

**Comment by nomadli** [comment]
i find the error
post.content have js code， so the result page is error

**Comment by benhowdle89** [comment]
Hey,

Not personally seen any errors with it, check it running here: http://benhowdle.im/jekyll-search-demo/search/?query=php

However, I can't promise it will work with newer versions of Jekyll, as I haven't updated it in a while!

**Comment by nomadli** [comment]
Thank you for your prompt reply，i test markdown have this code `<script>` `JavaScript` `</body>` and

**Comment by nomadli** [comment]
Thank you for your prompt reply。
i test markdown file is here https://github.com/Gaohaoyang/gaohaoyang.github.io/blob/master/_posts/2015-04-22-baidu-ife-2-javascript.md
the cotent have js code，I am prepared to avoid these codes im my makdown file。

Thank you for your prompt reply again

**Comment by benhowdle89** [comment]
Aha, I am sorry, I've only just understand what you're saying the issue was. Yes, that was unfortunately untested, and may have broke things. Sorry!
